// Button text constants
const BUTTON_TEXT_RELOAD = process.env.NEXT_PUBLIC_BUTTON_TEXT_RELOAD!;

// Error message constants
const ERROR_MSG_EXCEEDED_QUESTION_LIMIT =
  process.env.NEXT_PUBLIC_ERROR_MSG_EXCEEDED_QUESTION_LIMIT!;
const ERROR_MSG_QUESTION_GENERATION_FAILED =
  process.env.NEXT_PUBLIC_ERROR_MSG_QUESTION_GENERATION_FAILED!;
const ERROR_MSG_GENERIC = process.env.NEXT_PUBLIC_ERROR_MSG_GENERIC!;
const ERROR_MSG_NO_NUMBERS_IN_RANGE = process.env.NEXT_PUBLIC_ERROR_MSG_NO_NUMBERS_IN_RANGE!;
const ERROR_MSG_REACHED_QUESTION_LIMIT = process.env.NEXT_PUBLIC_ERROR_MSG_REACHED_QUESTION_LIMIT!;

// Success message constants
const SUCCESS_MSG_CORRECT_ANSWER = process.env.NEXT_PUBLIC_SUCCESS_MSG_CORRECT_ANSWER!;
const SUCCESS_MSG_INCORRECT_ANSWER = process.env.NEXT_PUBLIC_SUCCESS_MSG_INCORRECT_ANSWER!;

// Initial page constants
const INITIAL_PAGE_TITLE = process.env.NEXT_PUBLIC_INITIAL_PAGE_TITLE!;
const INITIAL_PAGE_SUBTITLE = process.env.NEXT_PUBLIC_INITIAL_PAGE_SUBTITLE!;
const INITIAL_PAGE_DESCRIPTION = process.env.NEXT_PUBLIC_INITIAL_PAGE_DESCRIPTION!;
const INITIAL_PAGE_ALTERNATING_TEXTS = process.env.NEXT_PUBLIC_INITIAL_PAGE_ALTERNATING_TEXTS!;

// Storage key constants
const STORAGE_KEY_QUIZ_RANGE = process.env.NEXT_PUBLIC_STORAGE_KEY_QUIZ_RANGE_KEY_NAME!;

// Business rule constants
const POINTS_ADJUSTMENT_RATE = process.env.NEXT_PUBLIC_POINTS_ADJUSTMENT_RATE!;

export {
  BUTTON_TEXT_RELOAD,
  ERROR_MSG_EXCEEDED_QUESTION_LIMIT,
  ERROR_MSG_QUESTION_GENERATION_FAILED,
  ERROR_MSG_GENERIC,
  ERROR_MSG_NO_NUMBERS_IN_RANGE,
  ERROR_MSG_REACHED_QUESTION_LIMIT,
  SUCCESS_MSG_CORRECT_ANSWER,
  SUCCESS_MSG_INCORRECT_ANSWER,
  INITIAL_PAGE_TITLE,
  INITIAL_PAGE_SUBTITLE,
  INITIAL_PAGE_DESCRIPTION,
  INITIAL_PAGE_ALTERNATING_TEXTS,
  STORAGE_KEY_QUIZ_RANGE,
  POINTS_ADJUSTMENT_RATE,
};
