const MSG_EXCEDEU_LIMITE_DE_PERGUNTAS_RESPONDIDAS = process.env.NEXT_PUBLIC_TEXT_MSG_EXCEDEU_LIMITE_DE_PERGUNTAS_RESPONDIDAS!;
const MSG_ERRO_AO_GERAR_PERGUNTA = process.env.NEXT_PUBLIC_TEXT_MSG_ERRO_AO_GERAR_PERGUNTA!;
const MSG_QUESTAO_RESPONDIDA_COM_SUCESSO = process.env.NEXT_PUBLIC_TEXT_MSG_QUESTAO_RESPONDIDA_COM_SUCESSO!;
const MSG_QUESTAO_INCORRETA = process.env.NEXT_PUBLIC_TEXT_MSG_QUESTAO_INCORRETA!;
const BUTTON_TEXT_RELOAD = process.env.NEXT_PUBLIC_TEXT_BUTTON_RELOAD!;
const MSG_ERRO_GENERICO = process.env.NEXT_PUBLIC_TEXT_MSG_ERRO_GENERICO!;
const MSG_ERRO_AO_GERAR_PERGUNTA_INTERVALO_INCORRETO = process.env.NEXT_PUBLIC_TEXT_MSG_ERRO_AO_GERAR_PERGUNTA_INTERVALO_INCORRETO!;
const TITULO_INITIAL_PAGE = process.env.NEXT_PUBLIC_INITIAL_PAGE_TITULO!;
const SUBTITULO_INITIAL_PAGE = process.env.NEXT_PUBLIC_INITIAL_PAGE_SUBTITULO!;
const DESCRICAO_INITIAL_PAGE = process.env.NEXT_PUBLIC_INITIAL_PAGE_DESCRICAO!;
const TEXTOS_ALTERNADOS_INITIAL_PAGE = process.env.NEXT_PUBLIC_INITIAL_PAGE_TEXTOS_ALTERNADOS!;
const LIMITE_QUANTIDADE_QUESTOES_CHAVE_NOME = process.env.NEXT_PUBLIC_STORAGE_KEY_QUIZ_RANGE_KEY_NAME!;
const MSG_LIMITE_QUESTOES_RESPONDIDAS = process.env.NEXT_PUBLIC_TEXT_MSG_ERROR_ATINGIU_LIMITE_DE_PERGUNTAS_RESPONDIDAS!;
const SUBTRAI_OU_ADICIONA_PONTOS_NAS_VARIAVEIS_DE_CONTROLE_DOS_TOPICOS = process.env.NEXT_PUBLIC_VARIAVEL_CONTROLA_DESCONTO_NOS_PONTOS!;

export {
    MSG_EXCEDEU_LIMITE_DE_PERGUNTAS_RESPONDIDAS,
    MSG_ERRO_AO_GERAR_PERGUNTA,
    MSG_QUESTAO_RESPONDIDA_COM_SUCESSO,
    MSG_QUESTAO_INCORRETA,
    BUTTON_TEXT_RELOAD,
    MSG_ERRO_GENERICO,
    MSG_ERRO_AO_GERAR_PERGUNTA_INTERVALO_INCORRETO,
    TITULO_INITIAL_PAGE,
    SUBTITULO_INITIAL_PAGE,
    DESCRICAO_INITIAL_PAGE,
    TEXTOS_ALTERNADOS_INITIAL_PAGE,
    LIMITE_QUANTIDADE_QUESTOES_CHAVE_NOME,
    MSG_LIMITE_QUESTOES_RESPONDIDAS,
    SUBTRAI_OU_ADICIONA_PONTOS_NAS_VARIAVEIS_DE_CONTROLE_DOS_TOPICOS
};