import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import { ThemeProvider } from '@/components/theme-provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'AWS Passei',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
  openGraph: {
    title: 'AWS Passei',
    description:
      'Quiz simples e prático para ajudar na preparação para a certificação AWS Certified Cloud Practitioner.',
    url: 'https://www.awspassei.com.br/',
    siteName: 'AWS Passei',
    images: [
      {
        url: 'https://qenlvudyxnc62dsc.public.blob.vercel-storage.com/banner-quiz',
        width: 1200,
        height: 630,
        alt: 'AWS Passei',
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster position="top-right" />
        </ThemeProvider>
      </body>
    </html>
  );
}
